name: fic17
description: Flutter Intensive Club batch 18.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.2.8
  image_picker: ^1.1.2
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/payments/
    - assets/images/order_status/
    - assets/icons/
    - assets/icons/alert/
    - assets/icons/nav/
    - assets/icons/home_resto/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
